name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
    - name: Build package
      run: uv build
    - name: Prepare release notes
      run: uv tool run git-changelog --release-notes > release-notes.md
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        body_path: release-notes.md
        files: dist/*
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
